/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PredictionInput = IDL.Record({
  'soilType' : IDL.Text,
  'temperature' : IDL.Float64,
  'humidity' : IDL.Float64,
  'rainfall' : IDL.Float64,
});
export const PredictionRecord = IDL.Record({
  'id' : IDL.Nat,
  'result' : IDL.Text,
  'plantingTime' : IDL.Text,
  'owner' : IDL.Principal,
  'generalGuidance' : IDL.Text,
  'timestamp' : IDL.Int,
  'fertilizerSuggestion' : IDL.Text,
  'input' : PredictionInput,
});

export const idlService = IDL.Service({
  'deletePrediction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getPredictions' : IDL.Func([], [IDL.Vec(PredictionRecord)], ['query']),
  'savePrediction' : IDL.Func([PredictionInput], [PredictionRecord], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PredictionInput = IDL.Record({
    'soilType' : IDL.Text,
    'temperature' : IDL.Float64,
    'humidity' : IDL.Float64,
    'rainfall' : IDL.Float64,
  });
  const PredictionRecord = IDL.Record({
    'id' : IDL.Nat,
    'result' : IDL.Text,
    'plantingTime' : IDL.Text,
    'owner' : IDL.Principal,
    'generalGuidance' : IDL.Text,
    'timestamp' : IDL.Int,
    'fertilizerSuggestion' : IDL.Text,
    'input' : PredictionInput,
  });
  
  return IDL.Service({
    'deletePrediction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getPredictions' : IDL.Func([], [IDL.Vec(PredictionRecord)], ['query']),
    'savePrediction' : IDL.Func([PredictionInput], [PredictionRecord], []),
  });
};

export const init = ({ IDL }) => { return []; };